### ISSUE TITLE
test amphora

### ISSUE THREAD

**Issue by zlemon819** [carbynestack/amphora#31]
hi, i am interested in your project and hope to learn your way of using  [MP-SPDZ](https://github.com/data61/MP-SPDZ) library, but there seem not exist any guidance in README. Could you give some explainations? 

Thank you.

**Comment by sbckr** [comment]
Hi @zlemon819
Thank you again for your interest in Carbyne Stack 😃

You can find more details on Carbyne Stack, its architecture and foundation on the [Overview](https://carbynestack.io/getting-started/overview/) page of https://carbynestack.io 

I very much invite you to join our Carbyne Stack Amphora [Discord channel](https://discord.gg/8ENpt835) for more detailed questions and general discussions.

Best regards,
Sebastian

**Comment by sbckr** [comment]
Amphora is using an additive secret sharing scheme when uploading and storing secrets, as it is used by MP-SPDZ. These secrets can then be provided to ephemeral as input when actually invoking a secure multiparty computation using MP-SPDZ.
